### ISSUE TITLE
Private resources visible in search

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/ArunaWeb#72]
In the search interface of the web UI, I can see "private" resources that were not created by me. Intuitively, I would expect that I can see only my own private resources and those of other users are hidden.

**Comment by das-Abroxas** [comment]
Hi Martin,
As we take a strict approach to the FAIR principles and open data, only resources with data class `Workspace` or `Confidential` are not listed in the search index. 

On the other hand, the non-personal metadata of resources with data class `Public` and `Private` is always listed in the public search index. The exceptions are labels that begin with `private` or `app.aruna-storage`, which are also filtered out beforehand. The important difference is that for a `Public` object, the actual uploaded data associated with the object can be downloaded without checking whether the user has sufficient permissions.

To request permissions for a resource within the system, the `RequestResourceAccessRequest` can be used, which sends a personal message to the creator of the resource.

If you have no further questions on this topic, I will close this issue as the search index is working as intended.

**Comment by mzur** [comment]
I see, so "private" and "public" are more like "restricted" and "open-access". Thanks for the explanation.
